import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import Loading from "../components/feature/loading";
import { GoogleTagManager } from "@next/third-parties/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="scroll-smooth">
      <body className="font-sans antialiased">
        <Suspense fallback={<Loading />}>
          <main
            className="relative min-h-screen bg-gradient-to-br from-purple-50 to-pink-50"
            data-testid="main-content"
          >
            {children}
            <GoogleTagManager gtmId="GTM-K55M4XSJ" />
          </main>
        </Suspense>
      </body>
    </html>
  );
}
